name: festymap
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^15.1.1
  wear: ^1.1.0
  android_alarm_manager_plus: ^3.0.4
  permission_handler: ^10.4.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
